### PR TITLE
[Fix] Codecov report uploads

### PR DESCRIPTION
**Pull request by eriese**
- the correct file is uploaded to codecov after tests pass
- codecov has a known rate limiter issue where it sometimes rejects the upload, so codecov upload failure doesn't fail the check
- lint checks prebuild instead of building everything. I'm not sure this is faster any, but it makes me feel better
- terser reporter now includes test-failure-collector's functionality, which moves that out of the `after` hook and into a listener that only runs on failures, which helps speed things up in the tests

### CODE REVIEW

**Comment by eriese** [comment]
@joostdecock , I'm done playing around with this and it can be merged

**Review by joostdecock — APPROVED** [review]

**Comment by joostdecock** [comment]
I'm trying 🤷

**Comment by eriese** [comment]
@joostdecock you might have to come to actual github to merge it?

**Comment by joostdecock** [comment]
Yeah well I don't seem to come around here too often 😂

**Pull request merged**
