### PR TITLE
New design 'Shelly', code

### PR DESCRIPTION
**Pull request by Thrunic**
This contains the code only for my new design 'Shelly.' The documentation will be in another PR.

### CODE REVIEW

**Comment by BenJamesBen** [comment]
This PR seems to be based off of `develop` and not off of `lab2.5`? Was this intended?

Because of this, I am not able to run the lab to test the design.

**Comment by Thrunic** [comment]
> This PR seems to be based off of `develop` and not off of `lab2.5`? Was this intended?
> 
> Because of this, I am not able to run the lab to test the design.

No, this is not intended. The lab was running at some point, but it's not now. I'm not sure what happened.

**Comment by Thrunic** [comment]
The lab should be working now.

**Comment by BenJamesBen** [comment]
Entirely optional, but if you want to add cutlist info to your parts, I believe it would be:
```diff
diff --git a/designs/shelly/src/back.mjs b/designs/shelly/src/back.mjs
index 10ffcf50eb..73829e4aec 100644
--- a/designs/shelly/src/back.mjs
+++ b/designs/shelly/src/back.mjs
@@ -114,6 +114,8 @@ function draftBack({
     })
   }
 
+  store.cutlist.addCut({ cut: 1 })
+
   if (complete) {
     snippets.armholeScoopEnd = new Snippet('bnotch', points.armholeScoopEnd)
 
diff --git a/designs/shelly/src/front.mjs b/designs/shelly/src/front.mjs
index 07d79d623d..71e0e440fd 100644
--- a/designs/shelly/src/front.mjs
+++ b/designs/shelly/src/front.mjs
@@ -93,6 +93,8 @@ function draftFront({
     })
   }
 
+  store.cutlist.addCut({ cut: 1 })
+
   if (complete) {
     snippets.armholeScoopEnd = new Snippet('notch', points.armholeScoopEnd)
 
diff --git a/designs/shelly/src/neckband.mjs b/designs/shelly/src/neckband.mjs
index 37981f0cb0..229d1a63eb 100644
--- a/designs/shelly/src/neckband.mjs
+++ b/designs/shelly/src/neckband.mjs
@@ -73,6 +73,8 @@ function draftNeckband({
     grainline: true,
   })
 
+  store.cutlist.addCut({ cut: 1 })
+
   if (complete) {
     points.title = new Point(neckbandLength / 4, neckbandWidth / 2)
     macro('title', { at: points.title, nr: 4, title: 'neckband' })
diff --git a/designs/shelly/src/raglansleeve.mjs b/designs/shelly/src/raglansleeve.mjs
index 9cc148bcc2..f1004e06f3 100644
--- a/designs/shelly/src/raglansleeve.mjs
+++ b/designs/shelly/src/raglansleeve.mjs
@@ -255,6 +255,8 @@ function draftRaglanSleeve({
     to: points.grainlineBottom,
   })
 
+  store.cutlist.addCut()
+
   if (complete) {
     snippets.frontArmholeScoopEnd = new Snippet('notch', points.frontArmholeScoopEnd)
     snippets.backArmholeScoopEnd = new Snippet('bnotch', points.backArmholeScoopEnd)
```

**Review by BenJamesBen — DISMISSED** [review]
I tested the PR in the lab, and it looks fine.

**Comment by Thrunic** [comment]
Cutlists have been added. designs.json is conflicting because the version in lab2.5 is very out of date.

**Comment by Thrunic** [comment]
Updating designs.json to the new format causes errors in the lab2.5, so I'm going to leave it with the conflict. My guess is that we'll have to wait until v3 comes out, unless someone has ideas on how to resolve this.

**Review by BenJamesBen — APPROVED** [review]

**Comment by Thrunic** [comment]
Closing this PR because I've put in a newer one based off of develop (v3) instead of lab2.5

**Pull request closed without merging**
