### PR TITLE
Fix broken macros documentation link

### PR DESCRIPTION
**Pull request by glennmatthews**
Just a quick pull request to fix a broken link I encountered while reading the documentation.

### CODE REVIEW

**Review by darigovresearch — APPROVED** [review]
Can confirm that there is a dead link at the below URL and that this fix world resolve this issue.

Thanks @glennmatthews for spotting this & making a pull request, would have merged this if we had access to the repo to do this!

https://freesewing.dev/howtos/code/macros

**Comment by starfetch** [comment]
Thanks @glennmatthews , nicely spotted! :)

**Comment by joostdecock** [comment]
@all-contributors please add @glennmatthews for doc

@starfetch @darigovresearch thank you so much for taking care of this.
As friendly reminder, we are an [all contributors](https://allcontributors.org/) project, so if you merge a PR, please make sure to add the author to our list of contributors.
If you're unsure how to do so, [check the docs](https://allcontributors.org/docs/en/bot/usage), or ping me.

**Comment by joostdecock** [comment]
@all-contributors please add @glennmatthews for doc

**Comment by joostdecock** [comment]
Note to self: Don't add any other ramblings when telling the bot what to do :wink:

**Pull request merged**
