### PR TITLE
Honor scale in plugin-theme.

### PR DESCRIPTION
**Pull request by nicholasdower**
Step 1 in addressing #1638.

[Example SVGs zip.](https://github.com/freesewing/freesewing/files/7870637/examples.zip)

## Scale equals 1
image

## Scale equals 3
image

## Questions for reviewers

- I left [paperless.scss](https://github.com/freesewing/freesewing/blob/develop/packages/plugin-theme/src/scss/paperless.scss) as is. Would you prefer I convert it to plain css and remove the sass build step? Also, it wasn't clear to me whether [sample.scss](https://github.com/freesewing/freesewing/blob/develop/packages/plugin-theme/src/scss/sample.scss) is used. I am happy to remove or convert.
- Any suggestions for how I could improve my test?
- I noticed there is already a `round` method in core utils. Should I be using that rather than copying it? I didn't find any examples of this being done.

### CODE REVIEW

**Comment by nicholasdower** [comment]
The tests are passing for me locally but failing in CI with:
```
ERROR: Error: Cannot find module '@babel/core'
```

**Comment by nicholasdower** [comment]
> The tests are passing for me locally but failing in CI with:
> 
> ```
> ERROR: Error: Cannot find module '@babel/core'
> ```

Just found 9aef8471472c0ec241de3b2d5db75a4386ecd3e9. Looks like you already fixed this! Thank you.

**Comment by nicholasdower** [comment]
> > The tests are passing for me locally but failing in CI with:
> > ```
> > ERROR: Error: Cannot find module '@babel/core'
> > ```
> 
> Just found [9aef847](https://github.com/freesewing/freesewing/commit/9aef8471472c0ec241de3b2d5db75a4386ecd3e9). Looks like you already fixed this! Thank you.

Actually this didn't resolve my issue. I tried rerunning the steps CI takes and was able to reproduce the issue. Installing `babel/core` manually resolved it. I see I am getting some warnings in CI:

```shell
npm WARN @freesewing/plugin-theme@2.19.9 requires a peer of @freesewing/core@^2.19.9 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/register@7.16.9 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @rollup/plugin-babel@5.3.0 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
``` 

I took a shot at addressing that in #1651 but I don't really know what I'm doing.

**Comment by nicholasdower** [comment]
> > The tests are passing for me locally but failing in CI with:
> > ```
> > ERROR: Error: Cannot find module '@babel/core'
> > ```
> 
> Just found [9aef847](https://github.com/freesewing/freesewing/commit/9aef8471472c0ec241de3b2d5db75a4386ecd3e9). Looks like you already fixed this! Thank you.

Actually, rebasing did not resolve my issue

**Comment by joostdecock** [comment]
You've been busy :)
I'm going to merge this as-is. Yes, I think it would make sense to port whatever SASS is there to plain CSS and avoid the pre-build step. Especially because node-sass requires native bindings which can sometimes cause the kind issues that are often hard to troubleshoot for people not so familiar with the JavaScript ecosystem.

So, merging this as-is and I've created #1656 for the SASS removal.

As for the questions:

> I left paperless.scss as is. Would you prefer I convert it to plain css and remove the sass build step? Also, it wasn't clear to me whether sample.scss is used. I am happy to remove or convert.

I've created #1656 for this. 

> Any suggestions for how I could improve my test?

> I noticed there is already a round method in core utils. Should I be using that rather than copying it? I didn't find any examples of this being done.

That's a good point, it hasn't been done, but could be done. I guess it would be DRYer that way, so let's take a stab at it.

**Comment by nicholasdower** [comment]
> You've been busy :) I'm going to merge this as-is. Yes, I think it would make sense to port whatever SASS is there to plain CSS and avoid the pre-build step. Especially because node-sass requires native bindings which can sometimes cause the kind issues that are often hard to troubleshoot for people not so familiar with the JavaScript ecosystem.
> 
> So, merging this as-is and I've created #1656 for the SASS removal.
> 
> As for the questions:
> 
> > I left paperless.scss as is. Would you prefer I convert it to plain css and remove the sass build step? Also, it wasn't clear to me whether sample.scss is used. I am happy to remove or convert.
> 
> I've created #1656 for this.

Thank you. I assigned it to myself and will pick it up next. 

> 
> > Any suggestions for how I could improve my test?
> 
> > I noticed there is already a round method in core utils. Should I be using that rather than copying it? I didn't find any examples of this being done.
> 
> That's a good point, it hasn't been done, but could be done. I guess it would be DRYer that way, so let's take a stab at it.

I'll have a go.

**Pull request merged**
