### PR TITLE
#2246 support imperial measurements in new measurement inputs

### PR DESCRIPTION
**Pull request by eriese**
Not quite ready, still need ideas for fixing an issue with imperial:

if the user is slow in typing a decimal, it may be converted to a fraction before they have completed their input.

#2246

### CODE REVIEW

**Comment by joostdecock** [comment]
Could we avoid all that by just not formatting the user's input?

Like, we want to display a nice fractions in the UI. But perhaps we leave the input as-is? 
Or perhaps we can trigger the formatting `onBlur` (when the input loses focus)

I'm thinking out loud here. I am happy to let you do it how you think is best. Just throwing ideas out there 😊

**Comment by eriese** [comment]
I'm up for that. Or, to be more specific, I think it works if we format
everything as decimals while allowing fraction inputs as long as the
fraction part of the input is <1

I'd like to hear from others, but I guess I could also just make it and
then it's in until someone asks for different

**Comment by joostdecock** [comment]
We're working on the future UI here. Nothing we do is going to break/change any UX people are familiar with today.

So I would vote for putting in place the things we've come up with here. We can tweak it or deal with corner cases later. It would already represent an great step forward.

So I would say go ahead.

I also wanted to ask if you'd be willing/open to take more responsibility within the project?
My feeling is that you're a better React developer than I am, and this is an area where there aren't many contributions. It would be nice to have someone to bounce ideas of and can also work independently to build a better experience.

I should perhaps work on my sales pitch, but my question is: how do you feel about more responsibility / a larger role in FreeSewing?

**Comment by joostdecock** [comment]
@eriese There's been a lot of changes in the repo structure. I'm still finalizing them and will update the docs. In the meanwhile, things are a bit broken and I'm sorry. Should be ok later today :see_no_evil:

**Comment by eriese** [comment]
No need to apologize! I believe this is properly merged and if you let me
know when it's all working again I can double check that

**Comment by joostdecock** [comment]
We're back in business 😊

New is `yarn tips`. Not related to this but feedback welcome

**Comment by eriese** [comment]
I'm gonna need to get a Vercel account, aren't I?

**Comment by joostdecock** [comment]
@eriese If you DM me your email address I can send you an invite for the Vercel team.

That being said, lab is broken right now because of the changes I did recently. I'm still putting it back on the rails.
In other words: It's not you, it's me :joy:

**Comment by joostdecock** [comment]
Please remind me @eriese where are we with this? Can this be merged?

**Comment by eriese** [comment]
Good to go!

**Pull request merged**
