### PR TITLE
fix: change twitter old icon with new X twitter icon

### PR DESCRIPTION
**Pull request by Regun63**

### CODE REVIEW

**Comment by joostdecock** [comment]
Hmm, this was already done by @TheTanay902 in #5203
However, I will merge this because:

- This path string is shorter yet visually it's the same
- We will be leaving Twitter anyway, the logo is already removed from our footer in favor of Mastodon on our beta site: https://next.freesewing.org/

That being said, I must admit that I am curious how such a seemingly small change attracts so many first-time contributors.
It's almost like it's a school assignment to find repos with outdated Twitter logos and then update them.

I don't know whether this is the case, but this is part of my reason for merging this. Because if it was a school assignment, then both @TheTanay902 and @biswassushmita947 deserve full marks :1st_place_medal:

**Comment by joostdecock** [comment]
@all-contributors please add @biswassushmita947 for code

**Comment by TheTanay902** [comment]
Hey @joostdecock 

This is ** totally** not a way to rack up quick contributions for the various open source contests we're having this month.

🫠😶‍🌫️

**Comment by joostdecock** [comment]
> Hey @joostdecock
> 
> This is ** totally ** not a way to rack up quick contributions for the various open source contests we're having this month. 👀
> 
> 🫠😶‍🌫️

Ah of course. I should have thought of that.
Well, I certainly appreciate it :+1:

**Comment by TheTanay902** [comment]
@joostdecock I had the chance to explore the project a bit, and it's certainly very unique and cool - also love the fact that it's so community driven. All the best to you and Freesewing, Joost!

**Pull request merged**
