### PR TITLE
Quality of Life update for Holmes

### PR DESCRIPTION
**Pull request by bobgeorgethe3rd**
Update to the Holmes Pattern

Additions
 - Head-Ease Option (Adding ease to head circumference)
- Ear-Length Option (Changes the length of the ear after lengthRatio has been applied)
- Ear-Width (Changes the width of the ear after headCircumference/12)
- Bill-Length Option (Alters sectorAngle to increase the overall length of the bill)

Changes
-Brim has been changed to Bill in both the code and the title
- Gore has been changed to Crown in the title.
- Ear is now Ear Flap in the title. (Note just changed so not in picture)
-Seam allowances now include hem which is twice the seam allowance (inner curve of bill, bottom of ear flap and crown)

### CODE REVIEW

**Comment by joostdecock** [comment]
Thank you for the PR, could you please make a few changes:

- The `version` field in the config file is a parameter that is loaded from package.json, please don't hard-code it
- To add two authors in the config, please use an array: `['person1', 'person2'],`
- We use `camelCase` for all option names, so don't use `head_ease` but rather `headEase` (for example)
- Can you explain why you changed `brim` to `bill`? Because I know what a brim is, but bill is a dude or something that needs to be paid to me.

tx

**Comment by bobgeorgethe3rd** [comment]
So Brim is defined by going around the entire head which is not what the pattern does.
Bill is defined the part of a cap that sticks out above the eyes of the person who is wearing it. It is interchangeable with Peak and Visor if that helps. I can also change it to one of these if prefered. Somone had changed the title of the piece to visor but not any of the options or the code itself. I changed it to make it easier to code upon as Stage 3 is making new patterns off of holmes so it is better for the long run.

**Comment by joostdecock** [comment]
Ok, I see. Then perhaps visor is a more accessible term. I've asked around, I have yet to find somebody who knows what `bill` is, so I think it's safe to assume that the majority of people will have no idea.

Visor on the other hand, I think is clear.

**Comment by bobgeorgethe3rd** [comment]
Also shall have to open up some requests for the markdown too now.

**Comment by joostdecock** [comment]
We good to release this updated version @bobgeorgethe3rd ?

**Comment by joostdecock** [comment]
Oh, and could you please summarize the changes so we can put them in the changelog?

**Comment by bobgeorgethe3rd** [comment]
Yep good to go

Additions
 - headEase Option (Adding ease to head circumference)
- earLength Option (Changes the length of the ear after lengthRatio has been applied)
- earWidth (Changes the width of the ear after headCircumference/12)
- visorLength Option (Alters sectorAngle to increase the overall length of the visor)
- buttonhole (Adds a buttonhole snippet to the ear flap starting at the crown length and going outwards, this is to allow for modifications to the ear flaps for the buttonhole variant described in the markdown)

Changes
-Brim has been changed to Visor in both the code and the title
- Gore has been changed to Crown in the title.
- Ear is now Ear Flap in the title.
- Seam allowances now include hem which is twice the seam allowance (inner curve of visor, bottom of ear flap and crown)

**Pull request merged**
