### PR TITLE
feat: Adds link to beginner pattern ideas from developer site

### LINKED ISSUE #1563: Link to beginner pattern ideas from developer site
To-do of #1514
Credits to @starfetch and @darigovresearch!

Add a link to [open issues with the label "pattern design" and "good first issue"](https://github.com/freesewing/freesewing/issues?q=is%3Aissue+is%3Aopen+label%3A%22%3Ashirt%3A+pattern+design%22+label%3A%22%3A%2B1%3A+good+first+issue%22+) on the developer site, the developer tutorial specifically.

### PR DESCRIPTION
**Pull request by darigovresearch**
Would resolve #1563 if merged

### CODE REVIEW

**Comment by joostdecock** [comment]
Could you make the link more descriptive? I'm not a fan of using `here` as link text 😉

**Comment by darigovresearch** [comment]
@joostdecock yeah sure, commit 3e770f31b5ef314fd206c2ea6354f8a2189d0312 should resolve this.

Thanks for the feedback!

**Comment by joostdecock** [comment]
Wonderful, thanks a bunch!

**Comment by darigovresearch** [comment]
You're very welcome, thanks for merging!

**Pull request merged**
