### PR TITLE
"New" Pattern Bob the bib

### LINKED ISSUE #1469: Add bib pattern to site
**What is it that you would like to see happen?**

When looking to learn how to make a pattern for #1431 we found the tutorial for how to make a bib pattern on the documentation site - https://freesewing.dev/tutorials/pattern-design/

Would like to see the bib sewing pattern in the site of the designs (https://freesewing.org/designs/) as it is a useful item of clothing & may be a good introductory sewing pattern for a new user or workshop. Also when the item is made it could potentially be "upcycled" into another item of clothing so the materials would not be wasted

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [x] No, I am not :thinking:

**Additional context**

Would be happy to make a pull request after replicating the bib after attempting the tutorial. Or if the code already exists somewhere to use that as the source to make a pull request. Is there an existing file that someone can point us to?

Also anybody who is new to contributing or interested in helping is welcome to join. See this video if you need some guidance on how you may be able to help - https://www.youtube.com/watch?v=UWA4wyacY2A

Suggested name is Bob the bib

### PR DESCRIPTION
**Pull request by darigovresearch**
Clones the current tutorial example code & Hortensia docs

If pull request is correct, would resolve #1469

Pull request references this example pull request for a new pattern being submitted - https://github.com/freesewing/freesewing/pull/1378

Assuming translation files will be automatically generated so only contains en.md docs files

This is the first pattern pull request so edits by maintainers has been enabled & may need extra care before merging, documentation for contributing pattern to site does not yet exist (#1515)

### CODE REVIEW

**Comment by joostdecock** [comment]
Thanks for the PR. I feel we should put this on the contributor call agenda, because this deviate a bit from the designs we typically have, so it might be good to have a discussion on the matter.

In any case, if we decide to add the bib, it should be a proper pattern. The tutorial splits the pattern up in various steps which is not what you'd want from a proper bib pattern.

**Comment by darigovresearch** [comment]
Thanks for taking a look at the pull request, happy to add this to the agenda for the contributor call for the 22nd when it gets set up. Could you advise which file is the ultimate pattern design & how to adjust it so we can switch it out in the meantime?

Couldn't find any docs on how to contribute so was using previous pull requests & other existing pattern folder format as a guide instead.

**Comment by joostdecock** [comment]
After the contributor call on the matter, I think the best option would be to extend the pattern, and remove the other parts.
If not, we'll be maintaining this code in two places forever.

I'd be happy to give you a quick outline on how to tackle such a thing.

**Comment by darigovresearch** [comment]
Yeah happy to take a look, you can message via discord to set it up using the voice chat or whatever works for you!

**Comment by joostdecock** [comment]
Implemented here: https://github.com/freesewing/freesewing/tree/develop/designs/bob

**Pull request closed without merging**
