### PR TITLE
fix(benjamin): Part name changes, instructions, and cutlist

### PR DESCRIPTION
**Pull request by BenJamesBen**
- Change part names for consistency and improvement, to make the pattern, cutting instructions, and construction instructions consistent in the names they use ("Bow", "Short Bow", "Medium Bow", "Long Bow, and "Collar Band").
- Improve and clarify instructions.
- Fix cutlist instructions (2 Medium Bow/Knot 2 and only 1 Long Bow/Knot 3).

### CODE REVIEW

**Review by woutervdub — APPROVED** [review]

**Comment by woutervdub** [comment]
I do wonder if we now should rename the `ribbon.mjs` to `collarBand.mjs` (and rename the functions within too). It seems inconsistent to not do so.

**Comment by BenJamesBen** [comment]
I don't think that renaming the file or functions is necessary, though we could do it if we want. They aren't visible to customers using the design or reading its documentation.

**Comment by BenJamesBen** [comment]
I moved this PR out of Draft status and changed its name.

**Comment by SeaZeeZee** [comment]
@joostdecock this one's been reviewed and is ready to merge!

**Comment by eriese** [comment]
While I'm emotionally with Wouter on renaming the files, it would also mean renaming the part exports, the parts, and their translation keys, so I think Ben's right and we skip it.

**Pull request merged**
