### PR TITLE
Updated tests for individual part drafting (aka the content option)

### PR DESCRIPTION
**Pull request by joostdecock**
This is inspired by @nicholasdower 's work on #1768

 - Step 1: Realize we should have unit tests to check that all individual patterns draft
 - Step 2: Realize you already added such tests
 - Step 3: Realize you configured them wrong
 
Submitting this as a PR because this breaks a bunch of tests. And while that is a good thing (1) it would not be great of we're stuck for the foreseeable future with a bunch of tests failing and people shrugging it off because *it's those `only` tests*

(1) Good in the sense that we can start chipping away at fixing those patterns that don't have their part dependencies properly configured (which is always the reason for this to fail)

**Does this catch all problems?**

Nick mentioned he wanted to use this with Simon, and it did not work as expected. Yet simon does not throw any errors.
Which makes me wonder if there's perhaps more to this than the draft failing.

Perhaps he can clarify what he expected and what happened instead.

### CODE REVIEW

**Comment by joostdecock** [comment]
Oops. Didn't realize I had a commit from late last night in here :see_no_evil:

**Comment by nicholasdower** [comment]
@joostdecock I was also trying to tackle this here: https://github.com/freesewing/freesewing/compare/nickd/simon-deps#files_bucket

**Comment by nicholasdower** [comment]
The problem seems to be that we aren't specifying the only setting correctly and that we aren't calling render. I made those changes and attempted to run all tests. Many failed so I am fixing them one by one.

Am I on the right track?

**Comment by nicholasdower** [comment]
All passing locally now. Opened https://github.com/freesewing/freesewing/pull/1771.

**Pull request closed without merging**
