### PR TITLE
German translation to diana added

### PR DESCRIPTION
**Pull request by SirCharlotte**

### CODE REVIEW

**Comment by joostdecock** [comment]
@SirCharlotte Thank you for helping out. Unfortunately our translations are handled with Crowdin, and if I'd merge this it would only get overwritten again.

Please check the translation guide: https://freesewing.dev/guides/translation
I'd be delighted to add you as a translator, if you'd like that.

**Comment by SirCharlotte** [comment]
@joostdecock Sorry for muddling this up. I'm currently working on my first pattern and thought it would be easier to make my first PR with something simple, like a translation. I just printed the diana pattern for sewing and saw that there wasn't a German translation yet. But if the translation workflow is completely different, I'd actually prefer to continue working on my pattern.

**Comment by joostdecock** [comment]
Sure thing 🙂

**Comment by starfetch** [comment]
@SirCharlotte I've taken the liberty and added your very nice translations to our crowdin project, so that they can show up on the site. Thanks a lot and good job! I'll also add you to our list of contributors.

**Comment by starfetch** [comment]
@all-contributors please add @SirCharlotte for translation

**Pull request closed without merging**
