### PR TITLE
feat(plugin-cutonfold): Set part cutonfold/grain in macro

### PR DESCRIPTION
**Pull request by joostdecock**
Requires #2502 to be merged

### CODE REVIEW

**Comment by joostdecock** [comment]
If somebody can explain to me why Holmes fails the tests here, I'd like to hear about it.

**Comment by eriese** [comment]
> If somebody can explain to me the design tests fail here, I'd like to hear about it.

not sure why, but here's the draft error:
```
Unable to draft part gore
TypeError: this.setCutOnFold is not a function
    at Part.cutonfold [as _macro_cutonfold] (webpack-internal:///../../plugins/plugin-cutonfold/src/index.js:37:18)
    at method (webpack-internal:///../../packages/core/src/part.js:48:59)
    at pattern.__WEBPACK_DEFAULT_EXPORT__ [as draftGore] (webpack-internal:///../../designs/holmes/src/gore.js:29:9)
    at Pattern.draft (webpack-internal:///../../packages/core/src/pattern.js:315:56)
```

**Review by BenJamesBen — APPROVED** [review]
I'm not sure about the test failures, but the code changes themselves look fine to me.

**Comment by joostdecock** [comment]
Ah, this relies on the changes in the previous PR.
Going to merge this and #2506 and then we should be good :crossed_fingers:

**Pull request merged**
