### PR TITLE
Convert Waralee from mm to snapped percentage options (Issue #1421)

### PR DESCRIPTION
**Pull request by woutervdub**

### CODE REVIEW

**Comment by darigovresearch** [comment]
@woutervdub Thanks for making a pull request & wanting to contribute to the project. Could you take a look at the automated checks and see if they can be resolved?

This would help make your pull request more likely to be merged

For convenience a link to issue #1421 which this is attempting to resolve can be found [here](https://github.com/freesewing/freesewing/issues/1421)

**Comment by joostdecock** [comment]
I noticed you converted the mm options to standard pct options, no snapping.
I don't think it matters all that much for the hem, but for the waistband width, I'd say it does.

Did you chose to do it this way for a specific reason? Or is it more due to unfamiliarity with the new snap settings?

**Comment by woutervdub** [comment]
That was both unfamiliarity, and just looking at how you solved it in Charlie. I’m not quite sure why it would matter in the waistband for Waralee, since that doesn’t use anything that should be sized. It’s just a slightly bigger hem. I don’t even line mine with anything. 

Wouter

**Comment by joostdecock** [comment]
Ok, sounds good. Merging this as the failing test is unrelated to this (and on my todo list)

**Pull request merged**
