### PR TITLE
Honor scale setting in scalebox.

### PR DESCRIPTION
**Pull request by nicholasdower**
## Approach
 1. Bound scale to the nearest of the following: 0.1, 0.2, 0.3, 0.4, 0.5. 0.6. 0.7, 0.8, 0.9, 1.0. 
 2. Choose an appropriate metric and imperial scalebox size, limited to half centimeter / eighth inch precision. 

[minibox-plus-scalebox.pdf](https://github.com/freesewing/freesewing/files/7908784/minibox-plus-scalebox.pdf)

### CODE REVIEW

**Comment by nicholasdower** [comment]
@joostdecock ptal when you have a chance. I am very open to changes or completely different approaches. Also, I have not yet fully digested https://github.com/freesewing/freesewing/discussions/1331. Once I do maybe a new path will become clear. Will start on tests tomorrow.

**Comment by nicholasdower** [comment]
In case we do end up going with this, I added a pdf which can be printed for testing. I will plan to go print it tomorrow and see that everything is as expected.

**Comment by nicholasdower** [comment]
I'm not sure about this build failure. All of the new issues look unrelated to this change:
image

**Review by joostdecock — COMMENTED** [review]
Flawless :+1:

**Comment by joostdecock** [comment]
> I'm not sure about this build failure. All of the new issues look unrelated to this change

Those are the downsides of a monorepo (and me not being too bother with pushing WIP code).
Don't worry, happy to merge this as it is. It's great.

**Comment by nicholasdower** [comment]
> > I'm not sure about this build failure. All of the new issues look unrelated to this change
> 
> Those are the downsides of a monorepo (and me not being too bother with pushing WIP code). Don't worry, happy to merge this as it is. It's great.

Great! I will try to make progress on tests today but I probably won't be able to print the PDF until tomorrow. Please feel free to do whatever is most convenient for you. If it unblocks you, feel free to merge.

**Comment by joostdecock** [comment]
I am going to close this, then re-open it. Just because it will trigger a re-run of the checks, and I'd like to get a new deepscan report.

**Comment by joostdecock** [comment]
TIP it will re-run all checks except the deepscan one :joy:

**Comment by nicholasdower** [comment]
> TIL it will re-run all checks except the deepscan one 😂

I force pushed and it looks like it is rerunning.

**Comment by nicholasdower** [comment]
> > TIL it will re-run all checks except the deepscan one 😂
> 
> I force pushed and it looks like it is rerunning.

Whoah! Now there are 157 new issues.

**Comment by joostdecock** [comment]
That's because I just fixed a bunch of linter warnings and it's comparing your branch against the fixed code now.

There were some issues in the auto-generated test code, so since it's generated for each packet, the count can go up quickly.
At least that's my excuse ;)

**Comment by nicholasdower** [comment]
Rebased and added a test. And now the build is green, nice. Marking this as ready for review.

**Comment by nicholasdower** [comment]
@joostdecock my plan is to do something similar though with fewer sizes for the miniscalebox but I think that could go in a separate PR. wdyt?

**Comment by nicholasdower** [comment]
I just noticed something strange with the inch symbols:
image

I used ["quotation marks"](https://unicode-table.com/en/0022/) (") in the code which resulted in the width measurement being displayed with a ["left double quotation mark"](https://unicode-table.com/en/201C/)  (“) and the height measurement being displayed with a ["quotation mark"](https://unicode-table.com/en/0022/) ("). According to https://en.wikipedia.org/wiki/Prime_(symbol) they should be ["double prime" symbols](https://unicode-table.com/en/search/?q=%E2%80%B3) (″).

Updated:
image

**Comment by nicholasdower** [comment]
Added miniscale. Here is a pdf with miniscale and scalebox for scales 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9 and 1.0:
[minibox-plus-scalebox.pdf](https://github.com/freesewing/freesewing/files/7908784/minibox-plus-scalebox.pdf)

**Comment by joostdecock** [comment]
Great work @nicholasdower :+1:

**Comment by nicholasdower** [comment]
FYI I printed this out today and everything measured up. 

One issue I noticed with the miniscale is that since the box is so small, it doesn't include any instructions about the imperial dimensions matching the outside box and the metric dimensions matching the inside. For the original measurements (1″ x 1″ and 2.5cm x 2.5xm) this doesn't matter since the lines are so close (0.01575 cm). But for smaller scales there is a risk of choosing dimensions which will produce two clearly distinct boxes. That might cause confusion. To avoid this, I attempted to choose dimensions where the distance between the imperial and metric box is very small. In some cases, that meant having the imperial box be slightly smaller than the metric box. 

```
metric, imperial, distance
  1cm,         ⅜″, -0.0187
1.3cm,         ½″, -0.01181
1.6cm,         ⅝″, -0.00492
1.9cm,         ¾″, +0.00197
2.2cm,         ⅞″, +0.00886
2.5cm,         1″, +0.01575
```

image

**Pull request merged**
