### PR TITLE
Lucy Documentation Re-Format

### PR DESCRIPTION
**Pull request by bobgeorgethe3rd**
Some Re-formatting of Lucy's Doc to bring in-line. I'll admit I got a little carried away with the instructions and made some additions.

### CODE REVIEW

**Comment by SeaZeeZee** [comment]
The instructions look good to me! I'm not sure I really jive with calling Lucy an exterior pocket though, it feels more accurate to call it a tie on pocket. Since these pockets don't have to be worn on the outside of your clothes and historically they weren't! 

When I am not on holiday I am planning to add some historical accuracy notes.

**Comment by joostdecock** [comment]
> _I'm not sure I really jive with calling Lucy an exterior pocket though_

No need to worry, I've pointed that out in the code review. 
The name in the translation files is **Lucy tie-on pocket** and it should be used consistently in the documentation.

If it doesn't get fixed by the time we're shipping this, I'll update it myself.

**Comment by bobgeorgethe3rd** [comment]
> I really jive with calling Lucy an exterior pocket.
I did ask you in discord clearly some slioght miscommunication my bad. Updated to Lucy tie-on pocket.

**Comment by SeaZeeZee** [comment]
> 

Yep I misunderstood what you were asking and why, thanks for changing it!

**Review by SeaZeeZee — APPROVED** [review]
Looks great now!

**Comment by joostdecock** [comment]
Seems I forgot to click the final submit on my review yesterday, but I had some small improvements so submitting them now, even if some of them are outdated

**Comment by joostdecock** [comment]
Made the changes myself. Merging.

**Pull request merged**
