### PR TITLE
Add panels option to Sandy

### PR DESCRIPTION
**Pull request by pvidas**

### CODE REVIEW

**Review by BenJamesBen — APPROVED** [review]
I tested the PR in the lab.

The new "Panels" design option seems to work correctly, producing the correct patterns and cutting instruction and continuing to obey the "Circle ratio" option.

I confirm that when the "Seamless full circle" design option is enabled, the pattern and cutting instructions are correct. The "Panels" option is simply ignored, similar to how "Circle ratio" is ignored.

FYI, for the i18n and documentation you do not have to create or edit the de/es/fr/nl/uk files. Instead, you simply create/edit the `en.md` files, and our translation process will automatically create and update the others.

(But, I think it's okay to include the extra language files in the PR? I'm not certain about this.)

Edit: Added: Actually, I'm now not sure about what I said about the i18n `json` files, since they are new in v3. I assumed that only the `en.json` file needed to be created since that is how things generally worked in the past. But, now I am not certain.

**Comment by BenJamesBen** [comment]
FYI, I've temporarily converted my PR #5859 to Draft status. I'll wait for this PR to be merged before fixing the dimensions issue.

**Review by joostdecock — APPROVED** [review]

**Comment by joostdecock** [comment]
@pvidas Thank you for this. Nicely done :pray: 

@BenJamesBen You are correct, updating the non-EN files is not required.
However, when starting a new design, you should copy the `en.json` to the other languages, because if the file is missing, the frontend will complain about failing to load it. But you can just keep the English content in them, as it will be replaced by crowdin.

**Comment by joostdecock** [comment]
@all-contributors please add @pvidas for code

**Comment by joostdecock** [comment]
@pvidas You will receive an invite to join the FreeSewing organisation on GitHub :tada: 
Doing so is completely optional, but if you do you will get triage rights on our repository, allowing you to label issues, assign them, and so on.

And it will look good on your GitHub profile :wink:

**Pull request merged**
