### PR TITLE
fix(dev,lab): Add <title> elements to HTML pages

### PR DESCRIPTION
**Pull request by BenJamesBen**
This is a partial fix for #3388 , for the dev and lab sites. (A separate PR will be filed for the org site.)

For freesewing.dev, the titles are the page titles with " - FreeSewing.dev" appended. For example: `Getting started with Gitpod - FreeSewing.dev` and `bartackFractionAlong - FreeSewing.dev`. The index page title is `Welcome to FreeSewing.dev`.

For lab.freesewing.dev, the titles for the lab are the capitalized design name or the design category text with " - FreeSewing Lab" appended. For example: `Simon - FreeSewing Lab` and `Block/Sloper Designs - FreeSewing Lab`. The index page title is `Welcome to the FreeSewing Lab`

### CODE REVIEW

**Review by eriese — CHANGES_REQUESTED** [review]
To avoid code duplication, I think this should happen in the `Page` wrapper located in `components/wrappers/page.js`, which all of these pages are using and handing a title prop.  According to the [`next/head docs`](https://nextjs.org/docs/api-reference/next/head) you can add `Head` anywhere, so while it feels counterintuitive to put a `<head>` into a `div`, in this case it's the cleanest thing to do

**Comment by joostdecock** [comment]
So, well spotted by @BenJamesBen that the title is missing, because it's a simple oversight. (eg `og:title` is set, but not the title tag).

And while @eriese makes a good point that we should keep things DRY so `components/wrappers/page.js` is the common place to add this, things get complicated fast.

For example, the open graph tags. On a blog post page, the image should be the image of the blog post. On a documentation page, the image should be one of the auto-generated OG images. On other pages the image should be *something else*. We also need to handle i18n in freesewing.org and lab, but not in dev. 
In general, each page of a similar *type* (like blog post of docs page, ...) has it's own page in the `pages` folder.

And I feel that in this particular instance it might make more sense to inline the abstraction rather than pass a bunch of props to the page wrapper and then do all sorts of stuff there.

So I am leaning more towards keeping things per-page, which is the way it's implemented now. Because while there will be some repetition, the added abstraction causes more mental overhead.

So I'm going to review this in that light, but I'm happy to debate further.

**Review by joostdecock — APPROVED** [review]

**Comment by eriese** [comment]
I'm not saying all things in `Head` need to be moved to `Page`, just that the title should be. It's already where the meta tag for title is. And then it can do the adding of the site name in just one place, because I see your Ben's point that it seems to be the done thing.

**Comment by joostdecock** [comment]
> I'm not saying all things in Head need to be moved to Page, just that the title should be.

Ah, I misunderstood.

**Comment by joostdecock** [comment]
Merged this as-is, then moved title to the dev site page wrapper in #3424

**Pull request merged**
