### PR TITLE
Lumira

### PR DESCRIPTION
**Pull request by woutervdub**
The new `lumira` leggings design. This is design one of two (`lumina` will follow shortly).

### CODE REVIEW

**Comment by woutervdub** [comment]
I guess I'll have to look at the `lint` errors....

**Comment by woutervdub** [comment]
This has to wait for #5652 to be implemented first. I'll have to commit a couple of files after that PR has been merged.

**Review by joostdecock — CHANGES_REQUESTED** [review]

**Comment by joostdecock** [comment]
@woutervdub Since I see that the lumira tests are currently failing, and that you added the `blocked` label, would you be so kind ping me if this is ready for review so I don't overlook this 🙏 
I'd like to put out a v3.1 release and I want this to go in it 😃

**Comment by woutervdub** [comment]
> @woutervdub Since I see that the lumira tests are currently failing, and that you added the `blocked` label, would you be so kind ping me if this is ready for review so I don't overlook this 🙏 I'd like to put out a v3.1 release and I want this to go in it 😃

I removed the `blocked` label. It passes all the tests now that I've brought my branch up-to-date with freesewing/develop. I'm not sure how I can force the tests on the PR to re-run.

**Comment by woutervdub** [comment]
Done, done, done. And done. 

On to the next design and hatever issues are still waiting for me.

**Pull request merged**
