### PR TITLE
Chore: Update `Point` dev docs

### LINKED ISSUE #1426: Document Point.dist()
It's missing somehow 🤷

### PR DESCRIPTION
**Pull request by sannek**
- Changed all titles to `Point.method()` instead of just `method()`
- Added a brief first paragraph description of each method
- Added subheadings to divide the page (to match what Joost did for some other docs)
- Added `Point.dist()` docs that got gitignored into oblivion
- Added a bit more detail to some of the docs that were a little confusing to me.

Closes #1426

### CODE REVIEW

**Comment by darigovresearch** [comment]
@sannek thanks for making a pull request to improve the dev docs. There appears to be an automatic check which is failing, could you take a look to see if you can resolve it?

**Comment by sannek** [comment]
> @sannek thanks for making a pull request to improve the dev docs. There appears to be an automatic check which is failing, could you take a look to see if you can resolve it?

Yeah I looked at that, and weirdly enough those issues are in files that I haven't touched at all? It seems a bit weird to make these changes in a docs only PR.

I wouldn't be surprised if it's caused by #1472 though, since I have not been able to pull or rebase anything for a long time, and even recloning the repository did not fix it.

**Comment by darigovresearch** [comment]
Thanks for taking a look, we're new to the development side of freesewing so we leave it to another more well versed contributor to freesewing to see if

- the error is relevant,
- your pull request resolves issue #1426 
- or if there is anything else required before your pull request is merged

Thanks again for taking the time to make the pull request!

**Comment by sannek** [comment]
> Thanks for taking a look, we're new to the development side of freesewing so we leave it to another more well versed contributor to freesewing to see if
> 
>     * the error is relevant,
> 
>     * your pull request resolves issue [Document Point.dist() #1426](https://github.com/freesewing/freesewing/issues/1426)
> 
>     * or if there is anything else required before your pull request is merged
> 
> 
> Thanks again for taking the time to make the pull request!

No worries - I tried some git magic to rebase on to `develop`, and that seems to have fixed the error 🎉

**Pull request merged**
