### PR TITLE
sleeve grainline alteration

### PR DESCRIPTION
**Pull request by SeaZeeZee**
Grainline point altered so grainline is straight.

### CODE REVIEW

**Comment by nicholasdower** [comment]
Looks great @SeaZeeZee! Thank you!

FYI your change only works for me if I revert the modification to `packages/simon/example/src/pattern`. Maybe that was included by mistake?

**Comment by SeaZeeZee** [comment]
Yep you're right, let me change that!

**Comment by nicholasdower** [comment]
Not sure whether I have the magic in me, but I think someone is supposed to say:

@all-contributors please add @SeaZeeZee for code

**Comment by SeaZeeZee** [comment]
Closed it because I cant quite figure out what happened and why it wanted to push that second commit.

**Pull request closed without merging**
