### PR TITLE
A few small Simon instruction updates

### PR DESCRIPTION
**Pull request by nicholasdower**
Dear Freesewing.org folks,

I've just had an amazing experience sewing the Simon shirt and would like to make a few small updates to the instructions. There are 6 separate commits:

- 741ead41ad0ccd72ad43013718eb045dc690d03e - Add the missing finished.gif file to the Simon directory. I copied the one in the Aaron directory as that seems to have been [the original intent](https://github.com/joostdecock/site/blame/1d4311d426739e87bb5dd4d32bc162a7eae0cfba/nuxt/content/en/docs/patterns/simon/index.md#L795).
- f621153ebf44e0bd9228ce1314be747770408bff - Remove the broken link to a YouTube video which was supposed to show how to fold the sleeve placket. This video is no longer available.
- 20c12a31547d7ef19bca96ad69801eca1eeb78b6 - Fix the broken collar-pressing image. It was linking to 19.png but should have linked to 19e.png.
- 66fa365e1ab7fca0a572c59d7524ef2fc53426d9 - Remove references to a non-existent sleeve notch. There are only two notches in the pattern (see [here](https://freesewing.org/create/simon/for/size-40-a/)), but three are referenced in the instructions.
- 608bab93c68727559198c2cf2a9bb3bdf57b130f - Fix the broken link to the sleevecap ease options page.
- 5bbcfa8b4cfce24c031cfbb79457d85fed413794 - Fix some typos (Happy to revert any that seem more like a style preference).

Thank you for taking the time to review my changes and thank you for the wonderful site!

Nick

### CODE REVIEW

**Review by darigovresearch — APPROVED** [review]
Hi @nicholasdower,

Glad to hear you had an amazing experience sewing with Simon & thanks for taking the time and wanting to improve the instructions with a pull request. Also congrats on your first pull request to this repository !

Everything seems good from our side, but will leave this open for any other maintainers to make any suggestions if needed (also we don't yet have merge rights on this repository).

You should consider joining the contributor call today if interested and free - https://github.com/freesewing/freesewing/issues/1580

**Comment by joostdecock** [comment]
@all-contributors please add @nicholasdower for docs

**Comment by joostdecock** [comment]
Thanks a bunch @nicholasdower :+1:

**Comment by nicholasdower** [comment]
Woohoo! Thanks for the quick reviews and warm welcome! I'm looking forward to the call.

**Pull request merged**
