### PR TITLE
Clarify the meaning of 'binding'

### PR DESCRIPTION
**Pull request by jdhoek**
The section on breast binding confused me at first due to the generic nature of the word 'binding'. This commit attempts to clarify this point to make it more readily understandable for a broader audience — hopefully without introducing exclusive or unsuitable language.

### CODE REVIEW

**Review by joostdecock — APPROVED** [review]
LGTM but going to run this by our trans ambassador

**Review by SeaZeeZee — CHANGES_REQUESTED** [review]
I think that adding 'breast' to the word binding is slightly redundant. I think however, I am not the kind of person to be confused. I think perhaps changing the word breasts to chest would read better though, since that is how it is generally used. 'Sally uses a binder to bind their chest.'

**Comment by joostdecock** [comment]
I have pinged our trans ambassador for a review of this PR. I think we can put a pin in this until that happens.

**Comment by jdhoek** [comment]
> I think that adding 'breast' to the word binding is slightly redundant. I think however, I am not the kind of person to be confused. I think perhaps changing the word breasts to chest would read better though, since that is how it is generally used. 'Sally uses a binder to bind their chest.'

Amended.

The confusion rises partly from the similar header above ('How it applies to patterns'); I was wondering what a 'binding' was in terms of sewing terminology primed by the 'patterns' above.

**Comment by KaerMorhan** [comment]
I do agree that using chest binding instead of breast binding might be a better fit. While breast binding is a phrase used by Wikipedia, most sources made by and aimed at transmasculine people use **chest binding**. Alternatively, both terms can be used as well - _if you are chest/breast binding_ - as cis girls/women also bind for different reasons (cosplay, comfort and aesthetics being some of them) and might use the phrase **breast binding** instead.

I am also not sure about _bound chest_ as I didn't encounter this phrase being used (usually it's _flattened_ or _compressed chest_, the former being more common) - might be useful to ask a native English speaker about this one.

Other than that, changes look good.

**Comment by SeaZeeZee** [comment]
Im also a non native speaker but have heard bound chest a lot. Language is fun! I can check with my US partner when they're awake.

**Review by joostdecock — APPROVED** [review]

**Comment by joostdecock** [comment]
Tx @KaerMorhan , merging

**Comment by joostdecock** [comment]
@all-contributors please add @jdhoek for docs

**Pull request merged**
