### PR TITLE
Making it more clear you need four pocket facings

### PR DESCRIPTION
**Pull request by TriploidTree**
I cut two, not paying close attention and then halfway through construction realised I needed 2x2 = 4

### CODE REVIEW

**Review by joostdecock — CHANGES_REQUESTED** [review]
This would make it say `4 x 2 pairs` which is 8 in total and unless I'm mistaken, that's incorrect.

So if we want to make it clearer, I feel we should do something like ` 4x (2 x 2 pairs)`

**Comment by TriploidTree** [comment]
I think the challenge is whether what's in bold can be used without the following text, so I read "x2" rather than "x2 pairs". 

Maybe `4x (2 matching pairs)`. or we move pairs into the bold so it reads as "x2 pairs" in bold, with the remainder unformatted?

**Comment by TriploidTree** [comment]
I think *4X* (2 x  2 sets with good sides together) might be a good compromise. 
If I read "2 pairs", I think 4 pieces, so "2x2 pairs" is 8, as a pair is already 2 parts. Isn't English fun. 

That said, I'm more interested in "4X" when reading a cutting list, so maybe 4X (2 x 2 pairs) would be fine as I'd ignore the part in brackets. I'm not sure whether that's an experienced sewist thing though.

**Comment by joostdecock** [comment]
Thank @TriploidTree

**Pull request merged**
