### PR TITLE
Draft: Extend brain for people with breasts and waist.

### PR DESCRIPTION
**Pull request by stsydow**
Extend brain for people with breasts and fit to waist.
Intended as a base block for stretch shirts and turtlenecks too.

This is a pretty extensive rework and a request for feedback.
It which would break other patterns if merged now.

Should this become a pattern of its own?

Also reworked the paperless mode.

### CODE REVIEW

**Comment by joostdecock** [comment]
Keeping an eye on this one :eyes: very happy to see some work on this

> Should this become a pattern of its own?

I feel that a block for stretch should probably become its own pattern. 
If for no other reason that it's more intuitive that way for people who are looking for a stretch block.

Perhaps a good middle ground would be to:

- Back-port those improvements that are meaningful for a woven block to Brian 
- Make the stretch block extend Brian so you can limit it to what matters

But I'm just thinking out loud here :)

**Comment by joostdecock** [comment]
@stsydow Are you keeping this in draft because you're still working on it, or to prevent it from accidentally getting merged (since it would indeed break a bunch of stuff).

I'm asking because I'm rather busy lately so I'll probably put this on the long finger for a closer look until I know you're ready with it :)

**Comment by stsydow** [comment]
All off the above :) This is a mixed bag because I want to make a pullover for my wife (the third one?) and this time I did not want to mess the paper draft to make it fit.

The following things are on my mind still:
 - [ ] a stretch fabric option 0% - 20% 
 - [ ] a pullover option with guaranties on  a wide enough waist and hip to pull it over in one piece. (waist without ease + stretch > chest/bust/(shoulder?)  
 - [ ] see what happens to other patterns based on Brian. 
 - [ ] `highBust` can become optional
 - [ ] fix docs
 - [ ] make a pullover and test out the realthing
 - [ ] seam allowance on the hem is broken

So I'm happy for anyone giving it a try, a rough review for things that sick out or even looking the example in #1360 to tell if the paperless mode looks good or needs improvement, is appreciated.

**Comment by joostdecock** [comment]
Hi @stsydow I've been trying to catch-up with some of the PRs that have gone somewhat stale, and this is one of them.

What do you propose to do with this effort?

**Comment by stsydow** [comment]
Sorry for the delay. Life has gotten in the way.
I will work on in but probably not in the next couple of weeks. 
So I'm fine when you want to close it.
If someone want's to reuse parts for other purposes that's also fine.
I could also explain things via phone if someone is interested, but I will not make it to  write up things 
in the meantime.

**Comment by joostdecock** [comment]
Since this is still v2 code, I'm closing this now as we're working towards a v3 release.
Thanks for your efforts @stsydow perhaps we can revisit this at some point in the future.

**Pull request closed without merging**
