### PR TITLE
Add `tristan` to FreeSewing

### LINKED ISSUE #5616: [feature]: include different dart shaping in Noble
### What is it that you would like to see happen? 🤔

I like my princess seams to do more of the shaping in the side panel, leaving the center front panel mostly straight on the side where it connects to the side front panel.  Carlita is a good example of the shaping I prefer.  It would be great if Noble could include that style of shaping as an option.  First comment will have a reference picture and information

### Are you a FreeSewing patron? 😃

Yes, I am a tier-2 patron ❤️

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by woutervdub**
New design collaboration. Top based on `noble`, can be turned into a dress by making a wide peplum.
Design by @nataliasayang, coding by @woutervdub 

NB. Also fixes #5616

### CODE REVIEW

**Review by BenJamesBen — CHANGES_REQUESTED** [review]
I tested this PR in the lab.

(I figured out that I have to run `yarn reconfigure` in order to get Tristan to appear on the localhost lab web page.)

As I understand it from looking at the design in the lab, Tristan is intended to always have a seam (or zipper or lacing) in the center back. There is no option where there is a seamless, cut-on-fold center back. (If these are both correct, then there is no issue. I'm just trying to understand the design intent.)

There is this seam allowance oddness at the bottom center back when Location of the Lacing is in the back and the Lacing Width is increased. It doesn't look quite right.
Screenshot 2024-01-22 at 9 57 56 PM

The waist seam allowance appears even if the Hem Option adds a hem. (I'm not sure whether or not this is correct behavior.)

**Comment by nataliasayang** [comment]
Thanks @BenJamesBen for your feedback on this. Much appreciated.

Responding to this:

> As I understand it from looking at the design in the lab, Tristan is intended to always have a seam (or zipper or lacing) in the center back. There is no option where there is a seamless, cut-on-fold center back. (If these are both correct, then there is no issue. I'm just trying to understand the design intent.)

Yes, that's correct. The back seam is shaped, so it's not intended to be cut on fold.

I agree with your other notes and edits. I'll let @woutervdub take them since I think they're all related to the code.

**Comment by woutervdub** [comment]
> There is this seam allowance oddness at the bottom center back when Location of the Lacing is in the back and the Lacing Width is increased. It doesn't look quite right.

Fixed 

> The waist seam allowance appears even if the Hem Option adds a hem. (I'm not sure whether or not this is correct behavior.)

Fixed

Thanks, @BenJamesBen !

**Comment by BenJamesBen** [comment]
Just some experimenting and playing around with the updated PR in the localhost lab, mostly testing the extremes of options using giant and doll models:

FYI, when using the cisFemaleGiant300 model using default options, there were 44 lacing holes in the front. When using the cisFemaleDoll60 model, there were 8 lacing holes. With cisMaleDoll10 and cisMaleDoll20, there were zero lacing holes front or back. With cisMaleDoll30, there were zero lacing holes in the front and 5 in the back.

***

Screenshot 2024-01-25 at 7 57 41 PM

```yaml
model: cisFemaleGiant300
measurements:
  ankle: 705
  biceps: 1050
  bustFront: 1680
  bustPointToUnderbust: 180
  bustSpan: 570
  chest: 3000
  crossSeam: 2610
  crossSeamFront: 1230
  crotchDepth: 1020
  heel: 1080
  head: 1770
  highBust: 3090
  highBustFront: 1710
  hips: 2520
  hpsToBust: 840
  hpsToWaistBack: 1410
  hpsToWaistFront: 1380
  inseam: 2340
  knee: 1230
  neck: 1140
  seat: 3060
  seatBack: 1680
  shoulderSlope: 13
  shoulderToElbow: 1080
  shoulderToShoulder: 1350
  shoulderToWrist: 1890
  underbust: 2940
  upperLeg: 1875
  waist: 2430
  waistBack: 1230
  waistToArmpit: 630
  waistToFloor: 3480
  waistToHips: 390
  waistToKnee: 1920
  waistToSeat: 810
  waistToUnderbust: 165
  waistToUpperLeg: 1020
  wrist: 525
units: metric
paperless: false
sabool: 1
sa: 10
samm: 10
options:
  hem: true
  waistDartLength: 0.75
  upperDartLength: 0.801
  highBustWidth: 0.8
  frontShoulderWidth: 0.92
  strapWidth: 0.05
  shoulderDartPosition: 0.1
  chestEase: 0.05
```
***

Screenshot 2024-01-25 at 8 00 34 PM

```yaml
model: cisFemaleGiant300
measurements:
  ankle: 705
  biceps: 1050
  bustFront: 1680
  bustPointToUnderbust: 180
  bustSpan: 570
  chest: 3000
  crossSeam: 2610
  crossSeamFront: 1230
  crotchDepth: 1020
  heel: 1080
  head: 1770
  highBust: 3090
  highBustFront: 1710
  hips: 2520
  hpsToBust: 840
  hpsToWaistBack: 1410
  hpsToWaistFront: 1380
  inseam: 2340
  knee: 1230
  neck: 1140
  seat: 3060
  seatBack: 1680
  shoulderSlope: 13
  shoulderToElbow: 1080
  shoulderToShoulder: 1350
  shoulderToWrist: 1890
  underbust: 2940
  upperLeg: 1875
  waist: 2430
  waistBack: 1230
  waistToArmpit: 630
  waistToFloor: 3480
  waistToHips: 390
  waistToKnee: 1920
  waistToSeat: 810
  waistToUnderbust: 165
  waistToUpperLeg: 1020
  wrist: 525
units: metric
paperless: false
sabool: 1
sa: 10
samm: 10
options:
  hem: true
  waistDartLength: 0.75
  upperDartLength: 0.95
  highBustWidth: 0.92
  frontShoulderWidth: 0.98
  strapWidth: 0.087
  shoulderDartPosition: 0.885
  chestEase: 0.05
  cutRoundnessFront: 1
  cutRoundnessBack: 1
  cutDepthFront: 1.25
  cutDepthBack: 0.05
  armholeDepth: 0.38
  waistEase: 0.01
  shoulderToShoulderEase: 0.05
  fullChestEaseReduction: 0.08
  bustSpanEase: -0.05
  waistdartposition: -1
  lacingLocation: back
  lacingWidth: 0.5
  zipperLocation: front
```
***

Screenshot 2024-01-25 at 8 04 10 PM
```yaml
model: cisFemaleGiant300
measurements:
  ankle: 705
  biceps: 1050
  bustFront: 1680
  bustPointToUnderbust: 180
  bustSpan: 570
  chest: 3000
  crossSeam: 2610
  crossSeamFront: 1230
  crotchDepth: 1020
  heel: 1080
  head: 1770
  highBust: 3090
  highBustFront: 1710
  hips: 2520
  hpsToBust: 840
  hpsToWaistBack: 1410
  hpsToWaistFront: 1380
  inseam: 2340
  knee: 1230
  neck: 1140
  seat: 3060
  seatBack: 1680
  shoulderSlope: 13
  shoulderToElbow: 1080
  shoulderToShoulder: 1350
  shoulderToWrist: 1890
  underbust: 2940
  upperLeg: 1875
  waist: 2430
  waistBack: 1230
  waistToArmpit: 630
  waistToFloor: 3480
  waistToHips: 390
  waistToKnee: 1920
  waistToSeat: 810
  waistToUnderbust: 165
  waistToUpperLeg: 1020
  wrist: 525
units: metric
paperless: false
sabool: 1
sa: 10
samm: 10
options:
  hem: true
  waistDartLength: 0.95
  upperDartLength: 0.931
  highBustWidth: 0.804
  frontShoulderWidth: 0.98
  strapWidth: 0.05
  shoulderDartPosition: 0.9
  chestEase: 0.162
  cutRoundnessFront: 0
  cutRoundnessBack: 0
  cutDepthFront: 1.25
  cutDepthBack: 0.9
  armholeDepth: 0.55
  waistEase: 0.111
  shoulderToShoulderEase: -0.009
  fullChestEaseReduction: 0.011
  bustSpanEase: 0.121
  waistdartposition: -1
  lacingLocation: back
  lacingWidth: 0.5
  zipperLocation: front
  hemSize: 0.243
```
***

Screenshot 2024-01-25 at 8 11 04 PM
```yaml
model: cisFemaleDoll60
measurements:
  ankle: 141
  biceps: 210
  bustFront: 336
  bustPointToUnderbust: 36
  bustSpan: 114
  chest: 600
  crossSeam: 522
  crossSeamFront: 246
  crotchDepth: 204
  heel: 216
  head: 354
  highBust: 618
  highBustFront: 342
  hips: 504
  hpsToBust: 168
  hpsToWaistBack: 282
  hpsToWaistFront: 276
  inseam: 468
  knee: 246
  neck: 228
  seat: 612
  seatBack: 336
  shoulderSlope: 13
  shoulderToElbow: 216
  shoulderToShoulder: 270
  shoulderToWrist: 378
  underbust: 588
  upperLeg: 375
  waist: 486
  waistBack: 246
  waistToArmpit: 126
  waistToFloor: 696
  waistToHips: 78
  waistToKnee: 384
  waistToSeat: 162
  waistToUnderbust: 33
  waistToUpperLeg: 204
  wrist: 105
sabool: 1
sa: 10
samm: 10
scale: '0.3'
options:
  lacingWidth: 0.5
  hem: true
  peplum: true
  zipperLocation: back
  peplumFullness: 360
  peplumSize: 0.624
  waistdartposition: 1
  bustSpanEase: -0.04
  chestEase: 0.2
  fullChestEaseReduction: 0.08
  shoulderToShoulderEase: 0.046
  waistEase: 0.2
  armholeDepth: 0.55
  cutDepthBack: 0.9
  cutDepthFront: 1.25
  cutRoundnessBack: 0
  cutRoundnessFront: 0
  shoulderDartPosition: 0.845
  strapWidth: 0.05
  frontShoulderWidth: 0.98
  highBustWidth: 0.92
  upperDartLength: 0.95
  waistDartLength: 0.929
```
***

Screenshot 2024-01-25 at 8 23 27 PM
```yaml
model: cisMaleDoll30
measurements:
  ankle: 70.5
  biceps: 105
  bustFront: 168
  bustPointToUnderbust: 18
  bustSpan: 57
  chest: 300
  crossSeam: 261
  crossSeamFront: 123
  crotchDepth: 102
  heel: 108
  head: 177
  highBust: 309
  highBustFront: 171
  hips: 252
  hpsToBust: 84
  hpsToWaistBack: 141
  hpsToWaistFront: 138
  inseam: 234
  knee: 123
  neck: 114
  seat: 306
  seatBack: 168
  shoulderSlope: 13
  shoulderToElbow: 108
  shoulderToShoulder: 135
  shoulderToWrist: 189
  underbust: 294
  upperLeg: 187.5
  waist: 243
  waistBack: 123
  waistToArmpit: 63
  waistToFloor: 348
  waistToHips: 39
  waistToKnee: 192
  waistToSeat: 81
  waistToUnderbust: 16.5
  waistToUpperLeg: 102
  wrist: 52.5
scale: '0.2'
options:
  waistdartposition: 1
  chestEase: 0.2
  shoulderToShoulderEase: 0.05
  strapWidth: 0.9
  shoulderDartPosition: 0.9
  frontShoulderWidth: 0.937
  highBustWidth: 0.823
  upperDartLength: 0.878
  waistDartLength: 0.942
  bustSpanEase: 0.115
  lacingWidth: 0.5
  lacingLocation: back
  fullChestEaseReduction: 0.003
  waistEase: 0.01
  armholeDepth: 0.477
  cutDepthBack: 0.05
  cutRoundnessBack: 1
```

**Comment by woutervdub** [comment]
> Just some experimenting and playing around with the updated PR in the localhost lab, mostly testing the extremes of options using giant and doll models:

Some of these were actually issues with the `noble` design, but I fixed them in this PR anyway. 

The weird inside-out thing with the `cisFemaleDoll60` I'm not trying to fix. It is such a user-induced issue that is really on the fringe, and it is too intensive to create a fix for it.

**Review by BenJamesBen — APPROVED** [review]
I tested Tristan again, and I think that it is ready to be merged for wider testing.

Other things I noticed:

The front/back center dotted line is still visible when `complete` is false. I'm not sure whether or not that is intended for the pattern.

I noticed that the "options" and "Peplum" menus change positions in Design Options when you enable/disable peplum and lacing. I think it's a side effect of how the UI is sorting/building menus. There is no specified expected behavior, so this isn't a bug. But, we might want to file a GitHub Issue later to address it.

I also notice that "options" isn't capitalized in the menu. I'm not sure why. Another menu UI thing to look at later.

The actual strap width seems to be limited depending on position of the shoulder dart. You can really see this if you set Width of the Straps to 100% and then slide Position of the Shoulder Dart from the default 50% to either 10% or 100%. At those Shoulder Dart positions, the strap width range is limited, as seen by sliding the Width of the Straps setting back and forth.

**Review by joostdecock — APPROVED** [review]

**Pull request merged**
