### PR TITLE
fix(boring-cyborg): Update the file paths and emojis used for PR labeling

### PR DESCRIPTION
**Pull request by nchilada**
`boring-cyborg` automatically adds labels to PRs based on which subdirectories are changed, but I think it's been missing all the subdirectories that have been relocated from `packages/` to elsewhere.

* Fixed:
  * `packages/config-helpers` (this was originally `packages/snapseries`)
  * `plugins/*` (these were originally found under `packages/`. give them a new emoji too.)
  * `sites/strapi` (this was originally found under `packages/`. give it a new emoji too.)
  * `designs/*` (these were originally found under `packages/`. give them a new emoji too)

* New:
  * `packages/new-design`, `packages/rehype-jargon`
  * `scripts`
  * `sites/*` (except for `strapi` which was originally found elsewhere)
  * `designs/bob`, `designs/hi`, `designs/lucy`, `designs/noble`, `designs/octoplushy`, `designs/plugintest`

### CODE REVIEW

**Comment by nchilada** [comment]
A couple notes:

* I assume this change does not apply retroactively. I.e. some labels will continue to be missing from recent PRs unless someone or somebot goes through and fixes them.
* ⚠️ This PR changes some of the PR labels (specifically, the choice of emoji) that are applied. That could cause problems if the old labels aren't updated in GitHub and in any other systems that rely on these. Alternatively, if anyone has better ideas for which emojis to use, I'm all ears

**Review by joostdecock — APPROVED** [review]

**Comment by joostdecock** [comment]
@nchilada you should have triage permissions know that you have joined the org. It should allow you to assign/remove labels.

I'm not certain whether it also allows you to manage labels, but it would be good to try it out.

**Comment by nchilada** [comment]
> @nchilada you should have triage permissions know that you have joined the org. It should allow you to assign/remove labels.
> 
> I'm not certain whether it also allows you to manage labels, but it would be good to try it out.

Hi @joostdecock, that is a great point. I think you're right, one ought to be able to rename old labels using [this page](https://github.com/freesewing/freesewing/labels) - as long as the desired label hasn't already been created (i.e. as long as we do this `boring-cyborg` starts doing it for too many new PRs), based on testing in one of my own repos. However, it looks like I don't have the requisite permissions in this repo right now, so that would have to be done by somebody else.
 
In any case, thank you for quickly reviewing and merging these PRs!

**Comment by nchilada** [comment]
…you know what, I half suspect I may have broken this config, since `boring-cyborg` hasn't commented at all on the PRs that have been created in the past day. I'm sorry! I don't have a lot to go off of but I'll check again later this week.

**Pull request merged**
