### PR TITLE
chore(docs): Add absoluteOptions setting documentation

### PR DESCRIPTION
**Pull request by BenJamesBen**

### CODE REVIEW

**Review by SeaZeeZee — CHANGES_REQUESTED** [review]
I wonder if its worth providing a concrete example here along with the signature?

**Comment by BenJamesBen** [comment]
Added example.

**Review by SeaZeeZee — APPROVED** [review]
Looks great now!

**Comment by BenJamesBen** [comment]
This partially covers #3232.

**Comment by SeaZeeZee** [comment]
@joostdecock This pr is also ready for merging

**Pull request merged**
