### PR TITLE
fix(workbench): renderProps in xray caused error as 'draft' was not part of props

### PR DESCRIPTION
**Pull request by luizfzs**
Before:
Screenshot from 2023-04-08 11-35-26

After:
Screenshot from 2023-04-08 11-38-00

### CODE REVIEW

**Review by joostdecock — APPROVED** [review]
LGTM

**Comment by joostdecock** [comment]
@luizfzs hey, thanks for your contribution. I noticed this is marked as draft. Is that intentional (as in, are you still working in it) or is it ready to be merged?

**Comment by luizfzs** [comment]
I was waiting for the build before making it ready for review and forgot to update it. 

It should be good to go now.

**Comment by joostdecock** [comment]
@all-contributors please add @luizfzs for code

**Pull request merged**
