### PR TITLE
Fix bug #5448

### PR DESCRIPTION
**Pull request by woutervdub**

### CODE REVIEW

**Comment by joostdecock** [comment]
Thanks for this @woutervdub I've added some more edge-cases that would fall victim to similar problems.
Could you check from your side that this (still) resolves your issue? :pray:

**Comment by woutervdub** [comment]
@joostdecock I'm getting errors that `partName` is undefined. But the `store` at the point of when the error is thrown, does contain this: `activePart: "noble.frontPoints"`, so I'm not sure what is going on.

**Comment by joostdecock** [comment]
@woutervdub Sorry for the delay. Can you check again now?

**Comment by woutervdub** [comment]
> @woutervdub Sorry for the delay. Can you check again now?

@joostdecock, you're using `removeGrain()` and `removeGrainline()`, while they should be the same thing. I don't know which term you prefer, so I didn't make any changes. My vote would be for `removeGrainline()`.

curonfold.mjs (38) `store.cutlist.removeGrainline()`
grainline.mjs (36) `store.cutlist.removeGrainline()`
cutlist.mjs (103) `function removeGrain(store)`

**Comment by joostdecock** [comment]
> @joostdecock, you're using `removeGrain()` and `removeGrainline()`, while they should be the same thing. I don't know which term you prefer, so I didn't make any changes. My vote would be for `removeGrainline()`.
> 
> curonfold.mjs (38) `store.cutlist.removeGrainline()` grainline.mjs (36) `store.cutlist.removeGrainline()` cutlist.mjs (103) `function removeGrain(store)`
> 
> Once this is resolved, all works fine for `tristan`.

Good catch. I think `removeGrainline` is a bit misleading as it seems to imply it would remove the grain line.
It does not. All it does is remove the data about the fabric gain in the store, which is a value in degrees. There is no line involved, or being removed.

So I've changed it to `removeGrain`, since it's also `setGrain` (and not `setGrainLine`).

**Pull request merged**
